# docker-compose

services:
  flask:
    build:
      context: ./api
      dockerfile: flask.Dockerfile
    expose:
      - "5000"
    env_file:
      - .env

  nginx:
    build:
      context: ./frontend
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - /etc/letsencrypt:/etc/nginx/certs:ro
    depends_on:
      - flask