
  export const TYPE = [
    'Scholarships/awards',
    'Financial need awards/bursaries',
    'Athletic awards',
    'Entrepreneurial awards',
    'International experience awards',
    'Other travel funding',
    'Research awards',
    'Medals/Prizes',
  ]

  export const LEVEL = [
    'Year One',
    'Year Two',
    'Year Three',
    'Year Four',
  ]

  export const AFFILIATION = [
    'Black',
    'Indigenous',
    'Mature learning',
    'Ontario first generation',
    'Part-time learner',
    'Refugee',
    'Varsity athlete',
    'Woman'
  ]

 export const FACULTY = [
    'Arts',
    'Engineering',
    'Environment',
    'Health',
    'Mathematics',
    'Science',
  ]
  
  export const PROGRAM = [
    'Open to any program',
    'Accounting and Financial Mgmt',
    'Anthropology',
    'Arts and Business',
    'Classical Studies',
    'Communication Arts',
    'Economics',
    'English Language and Literature',
    'Fine Arts',
    'French Studies',
    'Gender and Social Justice',
    'Germanic and Slavic Studies',
    'Global Business and Digital Arts',
    'History',
    'International Trade (minor)',
    'Liberal Studies',
    'Medieval Studies',
    'Music',
    'Peace and Conflict Studies',
    'Philosophy',
    'Political Science',
    'Psychology',
    'Religious Studies',
    'Sexuality, Relationships, and Families',
    'Social Development Studies',
    'Sociology and Legal Studies',
    'Spanish and Latin American Studies',
    'Sustainability and Financial Management',
    'Architecture',
    'Architectural Engineering',
    'Biomedical Engineering',
    'Chemical Engineering',
    'Civil Engineering',
    'Computer Engineering',
    'Electrical Engineering',
    'Environmental Engineering',
    'Geological Engineering',
    'Management Engineering',
    'Mechanical Engineering',
    'Mechatronics Engineering',
    'Nanotechnology Engineering',
    'Systems Design Engineering',
    'Software Engineering',
    'Climate and Environmental Change',
    'Environment and Business',
    'Environment, Resources and Sustainability',
    'Geography and Environmental Mgmt',
    'Geography and Aviation',
    'Geomatics',
    'International Development',
    'Knowledge Integration',
    'Planning',
    'Kinesiology',
    'Public Health and Health Sciences',
    'Recreation and Leisure Studies',
    'Computing and Financial Mgmt',
    'Actuarial Science',
    'Applied Mathematics',
    'Bioinformatics',
    'Business and CS (Double Degree)',
    'Business and Math (Double Degree)',
    'Combinatorics and Optimization',
    'Computational Mathematics',
    'Computer Science',
    'Data Science',
    'Information Technology Mgmt',
    'Math/Fin.Analysis and Risk Mgmt',
    'Mathematical Economics',
    'Mathematical Finance',
    'Mathematical Optimization',
    'Mathematical Physics',
    'Mathematics',
    'Mathematics/CPA',
    'Mathematics/Business Admin',
    'Mathematics/Teaching',
    'Pure Mathematics',
    'Scientific Computation/Applied Mathematics',
    'Statistics',
    'Biochemistry',
    'Biology',
    'Biomedical Sciences',
    'Biotechnology/CPA',
    'Biotechnology/Economics',
    'Chemistry',
    'Earth and Environmental Sciences',
    'Materials and Nanosciences',
    'Mathematical Physics',
    'Medicinal Chemistry',
    'Optometry',
    'Pharmacy',
    'Physics and Astronomy',
    'Psychology',
    'Science',
    'Science and Business',
    'Science and Aviation'
  ]

  export const TERM = ['Winter', 'Spring', 'Fall']

  export const CITIZENSHIP = ['Canadian citizen/permanent resident', 'International/study permit student', 'All Students']
  